# This file is machine-generated - editing it directly is not advised

julia_version = "1.7.3"
manifest_format = "2.0"

[[deps.Chakra]]
git-tree-sha1 = "cfd015347ace07b92ca9b6a9790159c10f15150b"
repo-rev = "main"
repo-url = "https://github.com/nick-harley/Chakra.git"
uuid = "23337c43-347c-4169-b193-f31a84c326bf"
version = "0.1.0"

[[deps.Charm]]
deps = ["Chakra"]
git-tree-sha1 = "5010271b18725d7efecb9a02d5dbe9a9eb1d4296"
repo-rev = "main"
repo-url = "https://github.com/nick-harley/Charm.git"
uuid = "e2273620-1c64-487a-88f9-b29e28f5a7be"
version = "0.1.0"
